title: The Fractured Spheres - Book of the players
baseurl: ""
sass:
  sass_dir: _sass
  style: compressed
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A d&d 5e campaign based in the world of Exandria and its content of Tal'Dorei.
  As you embark on your journey, tales of strange events and new discoveries are spreading like wildfire.
  Magical and physical anomalies are stirring curiosity and concern in equal measure.
  Prepare yourselves for an epic tale of discovery, danger, and destiny.
  Welcome to Tal'Dorei. Let the adventure begin!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  JanStaelens

# Build settings
theme: minima
plugins:
  - jekyll-feed